[theme]

primaryColor = "#0d3d66"  # dark blue
backgroundColor = "#FFFFFF"  # white
secondaryBackgroundColor = "rgba(228, 241, 254)"  # light blue
textColor = "#000000"  # black
font = "serif"

# Optional: Add a custom theme color for secondary text
[customTheme]
# secondaryTextColor = "#0d3d66"  # dark blue


